version: "3"
services:
  nginx:
    image: nginx
    working_dir: /www
    ports:
      - "80:80"
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./:/www:delegated
  php:
    image: lostdesign/laravel:1.2
    working_dir: /www
    volumes:
      - ./:/www:delegated
  mysql:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test123
  redis:
    image: redis
    ports:
      - "6382:6379"
  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
